name: Convert Markdown to HTML
on:
  push:
    branches:
      - '*'
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install pandoc
        run: sudo apt-get install -y pandoc
      - name: Convert Markdown to HTML
        run: pandoc -s -o index.html *.md
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Convert Markdown to HTML'
          commit_options: '--no-verify --signoff'
          commit_user_name: 'GitHub Action'
          commit_user_email: 'action@github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
