name: Convert Markdown to HTML

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install -y pandoc
      - name: Convert Markdown to HTML
        run: |
          for file in *.md
          do
            pandoc --from markdown --to html --output "${file%.*}.html" "$file"
          done
      - name: Commit and push changes
        run: |
          git config --local user.email "kakeru.hashimoto@lny.muratec.co.jp"
          git config --local user.name "KakeruHashimoto"
          git add .
          git commit -m "Convert Markdown to HTML"
          git push
